export const skills = [
    "Teamwork",
    "CSS BEM convention",
    "CSS Flex",
    "CSS Grid",
    "Error handling",
    "Git",
    "GitHub: Pull Requests & Review",
    "HTML",
    "Immutability",
    "JavaScript",
    "Local Storage",
    "Media Queries",
    "NPM",
    "Promises, Async/Await",
    "React",
    "React Hooks",
    "React Router",
    "Redux (Toolkit)",
    "Redux-Saga",
    "Redux Hooks",
    "Scrum",
    "Styled Components",
    "Time management",
    "Trello",
    "Figma",
    "Working with API (axios, fetch)",
];

export const toLearn = [
    "JS classes",
    "Node.js",
    "Next.js",
    "Tailwind CSS",
    "TypeScript",
    "Unit Testing",
    "Wordpress",
];